export const spotsList = {
  FETCH_SPOT_LIST_REQUEST: 'FETCH_SPOT_LIST_REQUEST',
  FETCH_SPOT_LIST_SUCCESS: 'FETCH_SPOT_LIST_SUCCESS',
  FETCH_SPOT_LIST_ERROR: 'FETCH_SPOT_LIST_ERROR',
};

export const FETCH_SPOT_REQUEST = 'FETCH_SPOT_REQUEST';
export const FETCH_SPOT_SUCCESS = 'FETCH_SPOT_SUCCESS';
export const FETCH_SPOT_ERROR = 'FETCH_SPOT_ERROR';

export const FETCH_SURF_FORECAST_REQUEST = 'FETCH_SURF_FORECAST_REQUEST';
export const FETCH_SURF_FORECAST_SUCCESS = 'FETCH_SURF_FORECAST_SUCCESS';
export const FETCH_SURF_FORECAST_ERROR = 'FETCH_SURF_FORECAST_ERROR';

export const CHANGE_SELECTED_DATETIME = 'CHANGE_SELECTED_DATETIME';