export const FETCH_SPOTS_REQUEST = 'FETCH_SPOTS_REQUEST';
export const FETCH_SPOTS_SUCCESS = 'FETCH_SPOTS_SUCCESS';
export const FETCH_SPOTS_ERROR = 'FETCH_SPOTS_ERROR';

export const FETCH_SPOT_DETAIL_REQUEST = 'FETCH_SPOT_DETAIL_REQUEST';
export const FETCH_SPOT_DETAIL_SUCCESS = 'FETCH_SPOT_DETAIL_SUCCESS';
export const FETCH_SPOT_DETAIL_ERROR = 'FETCH_SPOT_DETAIL_ERROR';

export const FETCH_SURF_FORECAST_REQUEST = 'FETCH_SURF_FORECAST_REQUEST';
export const FETCH_SURF_FORECAST_SUCCESS = 'FETCH_SURF_FORECAST_SUCCESS';
export const FETCH_SURF_FORECAST_ERROR = 'FETCH_SURF_FORECAST_ERROR';