export const Keys = {
  WAVE_DIRECTION: 'WAVE_DIRECTION',
  BREAK_TYPE: 'BREAK_TYPE',
  SWELL_EXPOSURE: 'SWELL_EXPOSURE',
  WIND_EXPOSURE: 'WIND_EXPOSURE',
  CROWDS: 'CROWDS',
  IS_PARKING: 'IS_PARKING',
  IS_TOILET: 'IS_TOILET',
  IS_BEGINNER_FRIENDLY: 'IS_BEGINNER_FRIENDLY',
  HANDLES_BIG_SWELL: 'HANDLES_BIG_SWELL',
  IS_CAMPING: 'IS_CAMPING',
  IS_LOCALISED: 'IS_LOCALISED',
};

export const Values = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  LEFT_AND_RIGHT: 'LEFT_AND_RIGHT',
  POINT: 'POINT',
  BEACH: 'BEACH',
  SAND: 'SAND',
  REEF: 'REEF',
  HIGH: 'HIGH',
  LOW: 'LOW',
};