# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Poseidon - Surf forecasts Victoria
email: nathanbirrell@gmail.com
description: Surf like a god with data-driven, spot-specific surf recommendations.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://surfposeidon.io" # the base hostname & protocol for your site

permalink: pretty

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: andrewbanchich
twitter_username: andrewbanchich
facebook_URL:
instagram_username:

# Build settings
markdown: kramdown
